import { TypedJson } from 'src/app/app.util';

export class ReturnReason {
    RMAActionCodeID: number;
    ReturnTypeID: number;
    RMAActionCode: string;
    RMAActionName: Reason;
    RMAActionTypeID: number;
    isActive: boolean;
    CreatedBy: number;
    CreatedDate: Date;
    ModifyBy: number;
    ModifyDate: Date;
    ReturnReasonRuleMapList: any;
    Scope: string;
    TenantReturnReasonCode: string;
    RequiredonCustomerPortal: boolean;
    RequiredonBackOffice: boolean;
    FileUploadRequired: boolean;
    CommentRequired: boolean;
    ApprovalRequired: boolean;
    ParentId: number;
    constructor()
    constructor(ReturnReason: ReturnReason)
    constructor(ReturnReason?: any) {
        this.ParentId = ReturnReason && ReturnReason.ParentId || 0;
        this.ReturnTypeID = ReturnReason && ReturnReason.ReturnTypeID || 0;
        this.RMAActionCode = ReturnReason && ReturnReason.RMAActionCode || 'AUTO';
        this.RMAActionTypeID = ReturnReason && ReturnReason.RMAActionTypeID || 0;
        this.isActive = ReturnReason && ReturnReason.isActive || true;
        this.CreatedBy = ReturnReason && ReturnReason.CreatedBy || 0;
        this.ModifyBy = ReturnReason && ReturnReason.ModifyBy || 0;
        this.CreatedDate = ReturnReason && ReturnReason.CreatedDate || null;
        this.ModifyDate = ReturnReason && ReturnReason.ModifyDate || null;
        this.ReturnReasonRuleMapList = ReturnReason && ReturnReason.ReturnReasonRuleMapList || [];
        this.Scope = ReturnReason && ReturnReason.Scope || null;
        this.TenantReturnReasonCode = ReturnReason && ReturnReason.TenantReturnReasonCode || null;
        this.RequiredonCustomerPortal = ReturnReason && ReturnReason.RequiredonCustomerPortal || null;
        this.RequiredonBackOffice = ReturnReason && ReturnReason.RequiredonBackOffice || null;
        this.FileUploadRequired = ReturnReason && ReturnReason.FileUploadRequired || null;
        this.CommentRequired = ReturnReason && ReturnReason.CommentRequired || null;
        this.ApprovalRequired = ReturnReason && ReturnReason.ApprovalRequired || null;
        this.RMAActionName = ReturnReason && ReturnReason.RMAActionName && new Reason(TypedJson.parse(ReturnReason.RMAActionName)) || new Reason();
    }
}

export class ReturnReasonRuleMap {
    ReturnReasonRuleMapID: number = 0;
    RMAActionCodeID: number = 0;
    RuleID: number = 0;
    RuleCode: string = "";
    ControlTypeID: number;
    ControlTypeName: string;
    RuleValue: string = "";
    RuleName: string = "";
    isOverRidable: boolean = false;
    isMandatory: boolean = false;
    isActive: boolean = true;
    CreatedBy: number;
    CreatedDate: Date;
    ModifyBy: number;
    ModifyDate: Date;
    TypeGroupControl: string;
    RoleControl: string;
    DamageControl: string;

}

export class Reason {
    enus: string;
    arsa: string;
    bgbg: string;
    caes: string;
    zhtw: string;
    cscz: string;
    dadk: string;
    dede: string;
    elgr: string;
    fifi: string;
    frfr: string;
    heil: string;
    huhu: string;
    isis: string;
    itit: string;
    jajp: string;
    kokr: string;
    nlnl: string;
    nbno: string;
    plpl: string;
    ptbr: string;
    roro: string;
    ruru: string;
    hrhr: string;
    sksk: string;
    sqal: string;
    svse: string;
    thth: string;
    trtr: string;
    urpk: string;
    idid: string;
    ukua: string;
    beby: string;
    slsi: string;
    etee: string;
    lvlv: string;
    ltlt: string;
    fair: string;
    vivn: string;
    hyam: string;
    azlatnaz: string;
    eues: string;
    mkmk: string;
    afza: string;
    kage: string;
    fofo: string;
    hiin: string;
    msmy: string;
    kkkz: string;
    kykg: string;
    swke: string;
    uzlatnuz: string;
    ttru: string;
    pain: string;
    guin: string;
    tain: string;
    tein: string;
    knin: string;
    mrin: string;
    sain: string;
    mnmn: string;
    gles: string;
    kokin: string;
    syrsy: string;
    dvmv: string;
    ariq: string;
    zhcn: string;
    dech: string;
    engb: string;
    esmx: string;
    frbe: string;
    itch: string;
    nlbe: string;
    nnno: string;
    ptpt: string;
    srlatncs: string;
    svfi: string;
    azcyrlaz: string;
    msbn: string;
    uzcyrluz: string;
    areg: string;
    zhhk: string;
    deat: string;
    enau: string;
    eses: string;
    frca: string;
    srcyrlcs: string;
    arly: string;
    zhsg: string;
    delu: string;
    enca: string;
    esgt: string;
    frch: string;
    ardz: string;
    zhmo: string;
    deli: string;
    ennz: string;
    escr: string;
    frlu: string;
    arma: string;
    enie: string;
    espa: string;
    frmc: string;
    artn: string;
    enza: string;
    esdo: string;
    arom: string;
    enjm: string;
    esve: string;
    arye: string;
    en029: string;
    esco: string;
    arsy: string;
    enbz: string;
    espe: string;
    arjo: string;
    entt: string;
    esar: string;
    arlb: string;
    enzw: string;
    esec: string;
    arkw: string;
    enph: string;
    escl: string;
    arae: string;
    esuy: string;
    arbh: string;
    espy: string;
    arqa: string;
    esbo: string;
    essv: string;
    eshn: string;
    esni: string;
    espr: string;
    smano: string;
    srcyrlba: string;
    zuza: string;
    xhza: string;
    fynl: string;
    tnza: string;
    sese: string;
    smase: string;
    filph: string;
    smnfi: string;
    quzpe: string;
    sefi: string;
    smsfi: string;
    cygb: string;
    hrba: string;
    iulatnca: string;
    bscyrlba: string;
    mohca: string;
    smjno: string;
    arncl: string;
    minz: string;
    quzec: string;
    gaie: string;
    rmch: string;
    srlatnba: string;
    smjse: string;
    lblu: string;
    nsza: string;
    quzbo: string;
    seno: string;
    mtmt: string;
    bslatnba: string;
    constructor()
    constructor(ReasonName: Reason)
    constructor(ReasonName?: any) {
        this.enus = ReasonName && ReasonName.enus || '';
        this.arsa = ReasonName && ReasonName.arsa || '';
        this.bgbg = ReasonName && ReasonName.bgbg || '';
        this.caes = ReasonName && ReasonName.caes || '';
        this.zhtw = ReasonName && ReasonName.zhtw || '';
        this.cscz = ReasonName && ReasonName.cscz || '';
        this.dadk = ReasonName && ReasonName.dadk || '';
        this.dede = ReasonName && ReasonName.dede || '';
        this.elgr = ReasonName && ReasonName.elgr || '';
        this.fifi = ReasonName && ReasonName.fifi || '';
        this.frfr = ReasonName && ReasonName.frfr || '';
        this.heil = ReasonName && ReasonName.heil || '';
        this.huhu = ReasonName && ReasonName.huhu || '';
        this.isis = ReasonName && ReasonName.isis || '';
        this.itit = ReasonName && ReasonName.itit || '';
        this.jajp = ReasonName && ReasonName.jajp || '';
        this.kokr = ReasonName && ReasonName.kokr || '';
        this.nlnl = ReasonName && ReasonName.nlnl || '';
        this.nbno = ReasonName && ReasonName.nbno || '';
        this.plpl = ReasonName && ReasonName.plpl || '';
        this.ptbr = ReasonName && ReasonName.ptbr || '';
        this.roro = ReasonName && ReasonName.roro || '';
        this.ruru = ReasonName && ReasonName.ruru || '';
        this.hrhr = ReasonName && ReasonName.hrhr || '';
        this.sksk = ReasonName && ReasonName.sksk || '';
        this.sqal = ReasonName && ReasonName.sqal || '';
        this.svse = ReasonName && ReasonName.svse || '';
        this.thth = ReasonName && ReasonName.thth || '';
        this.trtr = ReasonName && ReasonName.trtr || '';
        this.urpk = ReasonName && ReasonName.urpk || '';
        this.idid = ReasonName && ReasonName.idid || '';
        this.ukua = ReasonName && ReasonName.ukua || '';
        this.beby = ReasonName && ReasonName.beby || '';
        this.slsi = ReasonName && ReasonName.slsi || '';
        this.etee = ReasonName && ReasonName.etee || '';
        this.lvlv = ReasonName && ReasonName.lvlv || '';
        this.ltlt = ReasonName && ReasonName.ltlt || '';
        this.fair = ReasonName && ReasonName.fair || '';
        this.vivn = ReasonName && ReasonName.vivn || '';
        this.hyam = ReasonName && ReasonName.hyam || '';
        this.azlatnaz = ReasonName && ReasonName.azlatnaz || '';
        this.eues = ReasonName && ReasonName.eues || '';
        this.mkmk = ReasonName && ReasonName.mkmk || '';
        this.afza = ReasonName && ReasonName.afza || '';
        this.kage = ReasonName && ReasonName.kage || '';
        this.fofo = ReasonName && ReasonName.fofo || '';
        this.hiin = ReasonName && ReasonName.hiin || '';
        this.msmy = ReasonName && ReasonName.msmy || '';
        this.kkkz = ReasonName && ReasonName.kkkz || '';
        this.kykg = ReasonName && ReasonName.kykg || '';
        this.swke = ReasonName && ReasonName.swke || '';
        this.uzlatnuz = ReasonName && ReasonName.uzlatnuz || '';
        this.ttru = ReasonName && ReasonName.ttru || '';
        this.pain = ReasonName && ReasonName.pain || '';
        this.guin = ReasonName && ReasonName.guin || '';
        this.tain = ReasonName && ReasonName.tain || '';
        this.tein = ReasonName && ReasonName.tein || '';
        this.knin = ReasonName && ReasonName.knin || '';
        this.mrin = ReasonName && ReasonName.mrin || '';
        this.sain = ReasonName && ReasonName.sain || '';
        this.mnmn = ReasonName && ReasonName.mnmn || '';
        this.gles = ReasonName && ReasonName.gles || '';
        this.kokin = ReasonName && ReasonName.kokin || '';
        this.syrsy = ReasonName && ReasonName.syrsy || '';
        this.dvmv = ReasonName && ReasonName.dvmv || '';
        this.ariq = ReasonName && ReasonName.ariq || '';
        this.zhcn = ReasonName && ReasonName.zhcn || '';
        this.dech = ReasonName && ReasonName.dech || '';
        this.engb = ReasonName && ReasonName.engb || '';
        this.esmx = ReasonName && ReasonName.esmx || '';
        this.frbe = ReasonName && ReasonName.frbe || '';
        this.itch = ReasonName && ReasonName.itch || '';
        this.nlbe = ReasonName && ReasonName.nlbe || '';
        this.nnno = ReasonName && ReasonName.nnno || '';
        this.ptpt = ReasonName && ReasonName.ptpt || '';
        this.srlatncs = ReasonName && ReasonName.srlatncs || '';
        this.svfi = ReasonName && ReasonName.svfi || '';
        this.azcyrlaz = ReasonName && ReasonName.azcyrlaz || '';
        this.msbn = ReasonName && ReasonName.msbn || '';
        this.uzcyrluz = ReasonName && ReasonName.uzcyrluz || '';
        this.areg = ReasonName && ReasonName.areg || '';
        this.zhhk = ReasonName && ReasonName.zhhk || '';
        this.deat = ReasonName && ReasonName.deat || '';
        this.enau = ReasonName && ReasonName.enau || '';
        this.eses = ReasonName && ReasonName.eses || '';
        this.frca = ReasonName && ReasonName.frca || '';
        this.srcyrlcs = ReasonName && ReasonName.srcyrlcs || '';
        this.arly = ReasonName && ReasonName.arly || '';
        this.zhsg = ReasonName && ReasonName.zhsg || '';
        this.delu = ReasonName && ReasonName.delu || '';
        this.enca = ReasonName && ReasonName.enca || '';
        this.esgt = ReasonName && ReasonName.esgt || '';
        this.frch = ReasonName && ReasonName.frch || '';
        this.ardz = ReasonName && ReasonName.ardz || '';
        this.zhmo = ReasonName && ReasonName.zhmo || '';
        this.deli = ReasonName && ReasonName.deli || '';
        this.ennz = ReasonName && ReasonName.ennz || '';
        this.escr = ReasonName && ReasonName.escr || '';
        this.frlu = ReasonName && ReasonName.frlu || '';
        this.arma = ReasonName && ReasonName.arma || '';
        this.enie = ReasonName && ReasonName.enie || '';
        this.espa = ReasonName && ReasonName.espa || '';
        this.frmc = ReasonName && ReasonName.frmc || '';
        this.artn = ReasonName && ReasonName.artn || '';
        this.enza = ReasonName && ReasonName.enza || '';
        this.esdo = ReasonName && ReasonName.esdo || '';
        this.arom = ReasonName && ReasonName.arom || '';
        this.enjm = ReasonName && ReasonName.enjm || '';
        this.esve = ReasonName && ReasonName.esve || '';
        this.arye = ReasonName && ReasonName.arye || '';
        this.en029 = ReasonName && ReasonName.en029 || '';
        this.esco = ReasonName && ReasonName.esco || '';
        this.arsy = ReasonName && ReasonName.arsy || '';
        this.enbz = ReasonName && ReasonName.enbz || '';
        this.espe = ReasonName && ReasonName.espe || '';
        this.arjo = ReasonName && ReasonName.arjo || '';
        this.entt = ReasonName && ReasonName.entt || '';
        this.esar = ReasonName && ReasonName.esar || '';
        this.arlb = ReasonName && ReasonName.arlb || '';
        this.enzw = ReasonName && ReasonName.enzw || '';
        this.esec = ReasonName && ReasonName.esec || '';
        this.arkw = ReasonName && ReasonName.arkw || '';
        this.enph = ReasonName && ReasonName.enph || '';
        this.escl = ReasonName && ReasonName.escl || '';
        this.arae = ReasonName && ReasonName.arae || '';
        this.esuy = ReasonName && ReasonName.esuy || '';
        this.arbh = ReasonName && ReasonName.arbh || '';
        this.espy = ReasonName && ReasonName.espy || '';
        this.arqa = ReasonName && ReasonName.arqa || '';
        this.esbo = ReasonName && ReasonName.esbo || '';
        this.essv = ReasonName && ReasonName.essv || '';
        this.eshn = ReasonName && ReasonName.eshn || '';
        this.esni = ReasonName && ReasonName.esni || '';
        this.espr = ReasonName && ReasonName.espr || '';
        this.smano = ReasonName && ReasonName.smano || '';
        this.srcyrlba = ReasonName && ReasonName.srcyrlba || '';
        this.zuza = ReasonName && ReasonName.zuza || '';
        this.xhza = ReasonName && ReasonName.xhza || '';
        this.fynl = ReasonName && ReasonName.fynl || '';
        this.tnza = ReasonName && ReasonName.tnza || '';
        this.sese = ReasonName && ReasonName.sese || '';
        this.smase = ReasonName && ReasonName.smase || '';
        this.filph = ReasonName && ReasonName.filph || '';
        this.smnfi = ReasonName && ReasonName.smnfi || '';
        this.quzpe = ReasonName && ReasonName.quzpe || '';
        this.sefi = ReasonName && ReasonName.sefi || '';
        this.smsfi = ReasonName && ReasonName.smsfi || '';
        this.cygb = ReasonName && ReasonName.cygb || '';
        this.hrba = ReasonName && ReasonName.hrba || '';
        this.iulatnca = ReasonName && ReasonName.iulatnca || '';
        this.bscyrlba = ReasonName && ReasonName.bscyrlba || '';
        this.mohca = ReasonName && ReasonName.mohca || '';
        this.smjno = ReasonName && ReasonName.smjno || '';
        this.arncl = ReasonName && ReasonName.arncl || '';
        this.minz = ReasonName && ReasonName.minz || '';
        this.quzec = ReasonName && ReasonName.quzec || '';
        this.gaie = ReasonName && ReasonName.gaie || '';
        this.rmch = ReasonName && ReasonName.rmch || '';
        this.srlatnba = ReasonName && ReasonName.srlatnba || '';
        this.smjse = ReasonName && ReasonName.smjse || '';
        this.lblu = ReasonName && ReasonName.lblu || '';
        this.nsza = ReasonName && ReasonName.nsza || '';
        this.quzbo = ReasonName && ReasonName.quzbo || '';
        this.seno = ReasonName && ReasonName.seno || '';
        this.mtmt = ReasonName && ReasonName.mtmt || '';
        this.bslatnba = ReasonName && ReasonName.bslatnba || '';

    }
}